const initialState = {
  currDevice: null,
  list: [
    {
      _id: 101,
      name: 'Galaxy s7',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Samsung',
      operatingSystem: 'Android',
      publishDate: '2017',
      networkType: 'LTE',
      generation: 4,
      memory: '128GB',
      RAM: '6GB',
      processor: '2700 1800 MHz',
      location: { x: 40, y: 40 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 102,
      name: 'Galaxy Note 9',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Samsung',
      operatingSystem: 'Android',
      publishDate: '2018',
      networkType: 'LTE',
      generation: 4,
      memory: '128GB',
      RAM: '6GB',
      processor: '2700 1800 MHz',
      location: { x: 40, y: 40 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 103,
      name: 'iPhone 8',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2018',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 40, y: 40 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 104,
      name: 'iPhone 9',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2019',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 105,
      name: 'iPhone 10',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2020',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 106,
      name: 'iPhone 11',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2021',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 107,
      name: 'iPhone 12',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2022',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 108,
      name: 'iPhone 13',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2023',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 109,
      name: 'iPhone 14',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2024',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 110,
      name: 'iPhone 15',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2025',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 111,
      name: 'iPhone 16',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2026',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
    {
      _id: 112,
      name: 'iPhone 17',
      routers: [{ _id: 'R10', ip: '', location: { x: 190, y: 60 }, zIndex: 10 },
      { _id: 'R11', ip: '', location: { x: 140, y: 220 }, zIndex: 10 }],
      manufacturer: 'Apple',
      operatingSystem: 'iOS',
      publishDate: '2027',
      networkType: 'LTE',
      generation: 4,
      memory: '256GB',
      RAM: '4GB',
      processor: '2700 1800 MHz',
      location: { x: 20, y: 20 },
      zIndex: 10,
      isDraging: false,
    },
  ]
}

function getData() {
  return Promise.resolve(initialState)
}

export default {
  getData,
}
