
export const SET_HOME_DATA = 'SET_HOME_DATA'


export const SET_DEVICE_DATA = 'SET_DEVICE_DATA'
export const SET_CURR_DEVICE_BY_ID = 'UPDATE_CURR_DEVICE_BY_ID'
export const UPDATE_CURR_DEVICE = 'UPDATE_CURR_DEVICE'

export const SET_ROUTER_DATA = 'SET_ROUTER_DATA'

export const SET_SERVER_DATA = 'SET_SERVER_DATA'